[package]
name = "scrape-docs"
version = "0.1.0"
authors = ["Lonami Exo <totufals@hotmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.11.3"
tokio = { version = "1.5.0", features = ["full"] }
select = "0.5.0"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
futures = "0.3.14"
