[package]
name = "tl-to-json"
version = "0.1.0"
authors = ["Lonami Exo <totufals@hotmail.com>"]
edition = "2021"

[dependencies]
grammers-tl-parser = { path = "../../lib/grammers-tl-parser", version = "1.1.2" }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
